### ISSUE TITLE
Advertising as open source, but refusing to share the code

### ISSUE THREAD

**Issue by tedivm** [sparkfun/SparkFun_DataLogger_IoT_9DoF#3]
You can't have it both ways. Your website says this is "open hardware", but then in issue sparkfun/SparkFun_DataLogger#2 you're saying it's closed source.

<img width="570" alt="Screenshot 2023-07-19 at 1 10 38 PM" src="https://github.com/sparkfun/SparkFun_DataLogger_IoT_9DoF/assets/121709/1c0c594f-e3d8-43e8-9260-a24908cf403a">

<img width="428" alt="Screenshot 2023-07-19 at 1 11 06 PM" src="https://github.com/sparkfun/SparkFun_DataLogger_IoT_9DoF/assets/121709/523bf655-dc96-449c-be38-7c9257b59586">

You should issue refunds to the people who bought your hardware under false pretenses, and then stop with the false advertising.

**Comment by gigapod** [comment]
Hi @tedivm -

You are absolutely correct. 

The OSHWA logo/cert was a mistake made by our system when we build the board -- everything ran on automatic and it wasn't checked before the release. This has been resolved (we've de-registered the board with OSHWA) and updating the board silk to remove the logo. 

Everything in this repo (DataLogger_IoT_9DoF) is Open Source: The hardware designs and the example / testing firmware. 

The firmware that we flash on this board is managed in this repo :  [SparkFun DataLogger IoT](https://github.com/sparkfun/SparkFun_DataLogger). This is separate since we'll have multiple boards using the same firmware.

If we have missed any other location that is stating that the firmware source is available, please let us know and we'll get it corrected immediately. 

Thanks!
-Kirk

**Comment by tedivm** [comment]
I literally shared the screenshots of your website saying it's open source. Your website is still saying it, right now, today.

https://www.sparkfun.com/products/20594

Directly next to the product id you have the open source hardware logo, and if you click on that it says you will make the firmware available. This is literally what I shared in the screenshots at the top of the ticket.

Here's the full screenshot after you click the open source icon in the product listing:

<img width="1209" alt="Screenshot 2023-07-19 at 1 52 05 PM" src="https://github.com/sparkfun/SparkFun_DataLogger_IoT_9DoF/assets/121709/4e7cb28a-330a-4dd9-ae2d-1c4fce7379df">

**Comment by tedivm** [comment]
I also just want to say that I have a pile of Sparkfun components literally right next to me, and have been a customer for years. I'm really disappointed not only in the false advertising, but the move away from open source hardware as a whole. It definitely lowers my opinion of Sparkfun quite a bit.
